### ISSUE TITLE
How to animate parameter "Glitch!" ?

### ISSUE THREAD

**Issue by f00br** [keijiro/KinoDatamosh#4]
Hi Keijiro! I want to animate the "glitch!" parameter in the slate cinematic sequence(timeline alternative). Is it possible to do this on the timeline?

**Comment by keijiro** [comment]
It's possible with Timeline Signals.

https://blogs.unity3d.com/2019/05/21/how-to-use-timeline-signals/

Try invoking `Datamosh.Glitch()` from a timeline using a signal.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further issues.
